### ISSUE TITLE
should the blockchain know about nodes?

### ISSUE THREAD

**Issue by belun** [hoshsadiq/blockchain-go#4]
the concept of "node" is more networks related. maybe the server should know about these

blockchain knows of about blocks and future transactions (called CurrentTransactions). that should about enough

PS : is there a better way to communicate, instead of using "issues"? discord or slack?

**Comment by hoshsadiq** [comment]
Probably not, but this was easier than adding additional code. See the newly added readme and my reply on #2 for reasons this was written and this is also the reasons why I took a lot of short cuts that otherwise shouldn't be done.
